# Generated by Django 5.1.7 on 2025-03-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='reminder_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
