# Generated by Django 5.1.7 on 2025-03-09 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='completed_today',
            new_name='completed',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='reminder_time',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='streak',
        ),
    ]
