# Generated by Django 5.1.7 on 2025-03-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_habit_reminder_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='goal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
