# Generated by Django 5.1.7 on 2025-03-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_habit_goal_habit_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='completed_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
