# Generated by Django 5.1.7 on 2025-03-11 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_habit_completed_at'),
    ]

    operations = [
    ]
