# Generated by Django 5.1.7 on 2025-03-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_auto_20250311_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='streak',
            field=models.IntegerField(default=0),
        ),
    ]
